import type { NextPage } from 'next'
import { signIn, signOut, useSession } from 'next-auth/react'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  const session = useSession()
  return (
    <div className={styles.container}>
      <Head>
        <title>Hello, {session.data?.user?.name || 'stranger'}!</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Hello, {session.data?.user?.name || 'stranger'}!<br />
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>
        <p>
          {session.status === 'authenticated' ? (
            <button
              className={styles.button}
              type="button"
              onClick={() => signOut()}
            >
              Sign out {session.data.user?.email}
            </button>
          ) : (
            <button
              className={styles.button}
              type="button"
              onClick={() => signIn('spotify')}
              disabled={session.status === 'loading'}
            >
              Sign in with Spotify
            </button>
          )}
        </p>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export default Home
